// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaJogo.Data;

#nullable disable

namespace SistemaJogo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaJogo.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Poder")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TabelaPersonagen");

                    b.HasDiscriminator<string>("Classe").HasValue("Personagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaJogo.Models.Guerreiro", b =>
                {
                    b.HasBaseType("SistemaJogo.Models.Personagem");

                    b.HasDiscriminator().HasValue("Guerreiro");
                });

            modelBuilder.Entity("SistemaJogo.Models.Mago", b =>
                {
                    b.HasBaseType("SistemaJogo.Models.Personagem");

                    b.HasDiscriminator().HasValue("Mago");
                });
#pragma warning restore 612, 618
        }
    }
}
