// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAnimal.Data;

#nullable disable

namespace SistemaAnimal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113112936_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAnimal.Models.Animal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("TipoAnimal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TabelaAnimal");

                    b.HasDiscriminator<string>("TipoAnimal").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaAnimal.Models.Elefante", b =>
                {
                    b.HasBaseType("SistemaAnimal.Models.Animal");

                    b.HasDiscriminator().HasValue("Elefante");
                });

            modelBuilder.Entity("SistemaAnimal.Models.Leao", b =>
                {
                    b.HasBaseType("SistemaAnimal.Models.Animal");

                    b.HasDiscriminator().HasValue("Leao");
                });
#pragma warning restore 612, 618
        }
    }
}
